baseURL = "http://jasonkincl.com/"
languageCode = "en-us"
copyright = "Copyright &copy; 2021 - Jason Kincl"
title = "Personal Blog"

theme = "kiera"
# kiera theme options
pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Jason Kincl"
    github = "kincl"
    gitlab = ""
    linkedin = "jasonkincl"
    facebook = ""
    twitter = ""
    instagram = ""

[params]
    tagline = "personal blog"
