baseURL = "http://jasonkincl.com/"
languageCode = "en-us"
copyright = "Copyright &copy; 2018 - Jason Kincl"
title = "A Blog"

theme = "kiera"
# kiera theme options
pygmentsCodeFences = true

disqusShortname = "" #Disqus shortname
googleAnalytics = "" #Google Analytics ID

[author]
    name = "Jason Kincl"       #Author name
    github = "kincl"     #Github username
    gitlab = ""     #Gitlab username
    linkedin = "jasonkincl"   #LinkedIn username
    facebook = ""   #Facebook username
    twitter = ""    #Twitter username
    instagram = ""  #Instagram username

[params]
    tagline = "a systems engineering blog"
# kiera theme options
